spring.application.name=proauth
spring.mongodb.uri=mongodb+srv://satiiifalguni_db_user:rCZcuhm2U4k3hc0c@procluster.rogjxow.mongodb.net/authdb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
server.port=8080