spring.application.name=proauth
spring.data.mongodb.uri=mongodb+srv://satiiifalguni_db_user:rCZcuhm2U4k3hc0c@cluster0.bullfhc.mongodb.net/authdb?authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
server.port=8080


