spring.application.name=proauth
spring.mongodb.uri=mongodb+srv://<Username:Password>@procluster.rogjxow.mongodb.net/authdb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
server.port=8080
jwt.secret=<JWT_SECRETS>
jwt.expiration=86400000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
